const eventos = [
    {
      imagen: "",
      titulo: "Concierto en Vivo",
      fecha: "2023-12-01",
      entradaDisponible: true,
      ubicacion: "Teatro Principal",
    },
    {
      imagen: "ruta_a_la_imagen2.jpg",
      titulo: "Festival de Arte",
      fecha: "2023-11-15",
      entradaDisponible: false,
      ubicacion: "Centro de Convenciones",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
      },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
    {
        imagen: "ruta_a_la_imagen1.jpg",
        titulo: "Concierto en Vivo",
        fecha: "2023-12-01",
        entradaDisponible: true,
        ubicacion: "Teatro Principal",
    },
];